## public routing.
ns_resume_homepage:
    path:     /{page}
    defaults:
        _controller: NSResumeBundle:Public:index
        page: 1
    requirements:
        page: \d*
    methods: GET

ns_resume_details:
    path: /{slug}-{id}.html
    defaults:
        _controller: NSResumeBundle:Public:details
    requirements:
        slug: .+
        id: \d+
    methods: GET
