<?php

namespace Com\Nairus\ResumeBundle\Repository;

/**
 * AvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvatarRepository extends \Doctrine\ORM\EntityRepository
{
}
