<?php

namespace Com\Nairus\ResumeBundle\Repository;

/**
 * ResumeSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResumeSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
