<?php

namespace Com\Nairus\ResumeBundle\Entity;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-10 at 13:13:10.
 */
class AvatarTest extends KernelTestCase
{

    /**
     * @var Avatar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Avatar();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::setImageSrcPath
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::getImageSrcPath
     */
    public function testGetAndSetImageSrcPath()
    {
        try {
            $imagePath = "/path/to/image.png";
            $this->object->setImageSrcPath($imagePath);
            $this->assertSame($imagePath, $this->object->getImageSrcPath());

            // Tests PHP 7 :
            $this->object->setImageSrcPath(true); // typecasting en (string)"1"
            $this->object->setImageSrcPath(false); // typecasting en (string)""
            $this->object->setImageSrcPath(42); // typecasting en (string)"42"
            $this->object->setImageSrcPath(1.5); // typecasting en (string)"1.5"
            $this->object->setImageSrcPath(0); // typecasting en (string)"0"
        } catch (\Exception $exc) {
            $this->fail("Aucune exception ne doit être levé: " . $exc->getMessage());
        } catch (\Error $err) {
            $this->fail("Aucune erreur ne doit être levée :" . $err->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::setImageSrcPath
     *
     * @expectedException \TypeError
     */
    public function testSetImageSrcPathWithNullParam()
    {
        $this->object->setImageSrcPath(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::setImageSrcPath
     *
     * @expectedException \TypeError
     */
    public function testSetImageSrcPathWithBadParam()
    {
        $this->object->setImageSrcPath(array());
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::setImageThbPath
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::getImageThbPath
     */
    public function testGetAndSetImageThbPath()
    {
        try {
            $imagePath = "/path/to/image.png";
            $this->object->setImageThbPath($imagePath);
            $this->assertSame($imagePath, $this->object->getImageThbPath());
        } catch (\Exception $exc) {
            $this->fail("Aucune exception ne doit être levé: " . $exc->getMessage());
        } catch (\Error $err) {
            $this->fail("Aucune erreur ne doit être levée :" . $err->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::setImageThbPath
     *
     * @expectedException \TypeError
     */
    public function testSetImageThbPathWithBadParam()
    {
        $this->object->setImageThbPath(array());
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::setProfile
     * @covers Com\Nairus\ResumeBundle\Entity\Avatar::getProfile
     */
    public function testGetAndSetProfile()
    {
        try {
            $profile = new Profile();
            $this->object->setProfile($profile);
            $this->assertSame($profile, $this->object->getProfile());
        } catch (\Exception $exc) {
            $this->fail("Aucune exception ne doit être levé: " . $exc->getMessage());
        } catch (\Error $err) {
            $this->fail("Aucune erreur ne doit être levée :" . $err->getMessage());
        }
    }

}
