<?php

namespace Com\Nairus\ResumeBundle\Entity;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Com\Nairus\UserBundle\Entity\User;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-11 at 16:47:53.
 */
class ProfileTest extends KernelTestCase {

    /**
     * @var Profile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Profile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setPhone
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getPhone
     */
    public function testGetAndSetPhone() {
        try {
            $this->object->setPhone("04.01.01.01.01");
            $this->assertSame("04.01.01.01.01", $this->object->getPhone());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setPhone
     *
     * @expectedException \TypeError
     */
    public function testSetPhoneWithNullParam() {
        $this->object->setPhone(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setCell
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getCell
     */
    public function testGetAndSetCell() {
        try {
            $this->object->setCell("06.01.01.01.01");
            $this->assertSame("06.01.01.01.01", $this->object->getCell());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setCell
     *
     * @expectedException \TypeError
     */
    public function testSetCellWithNullParam() {
        $this->object->setCell(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setAddress
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getAddress
     */
    public function testGetAndSetAddress() {
        try {
            $this->object->setAddress("Adresse 1");
            $this->assertSame("Adresse 1", $this->object->getAddress());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setAddress
     *
     * @expectedException \TypeError
     */
    public function testSetAddressWithNullParam() {
        $this->object->setAddress(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setAddressAddition
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getAddressAddition
     */
    public function testGetAndSetAddressAddition() {
        try {
            $this->object->setAddressAddition("Adresse 2");
            $this->assertSame("Adresse 2", $this->object->getAddressAddition());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setAddressAddition
     *
     * @expectedException \TypeError
     */
    public function testSetAddressAdditionWithNullParam() {
        $this->object->setAddressAddition(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setCity
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getCity
     */
    public function testGetAndSetCity() {
        try {
            $this->object->setCity("Marseille");
            $this->assertSame("Marseille", $this->object->getCity());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setCity
     *
     * @expectedException \TypeError
     */
    public function testSetCityWithNullParam() {
        $this->object->setCity(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setZip
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getZip
     */
    public function testGetAndSetZip() {
        try {
            $this->object->setZip("13004");
            $this->assertSame("13004", $this->object->getZip());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setZip
     *
     * @expectedException \TypeError
     */
    public function testSetZipWithNullParam() {
        $this->object->setZip(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setCountry
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getCountry
     */
    public function testGetAndSetCountry() {
        try {
            $this->object->setCountry("France");
            $this->assertSame("France", $this->object->getCountry());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setCountry
     *
     * @expectedException \TypeError
     */
    public function testSetCountryWithNullParam() {
        $this->object->setCountry(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getFirstName()
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setFirstName()
     */
    public function testGetAndSetFirstName() {
        try {
            $this->object->setFirstName("Prénom");
            $this->assertSame("Prénom", $this->object->getFirstName());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setFirstName()
     *
     * @expectedException \TypeError
     */
    public function testSetFirstNameWithNullParam() {
        $this->object->setFirstName(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getLastName()
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setLastName()
     */
    public function testGetAndSetLastName() {
        try {
            $this->object->setLastName("Nom");
            $this->assertSame("Nom", $this->object->getLastName());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setLastName()
     *
     * @expectedException \TypeError
     */
    public function testSetLastNameWithNullParam() {
        $this->object->setLastName(null);
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::setUser
     * @covers Com\Nairus\ResumeBundle\Entity\Profile::getUser
     */
    public function testGetAndSetUser() {
        try {
            $user = new User();
            $this->object->setUser($user);
            $this->assertSame($user, $this->object->getUser());
        } catch (\Exception | \Error $exc) {
            $this->fail("Aucune exception/erreur ne doit être levé: " . $exc->getMessage());
        }
    }

}
