<?php

namespace Com\Nairus\ResumeBundle\Entity;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-11 at 16:48:13.
 */
class SkillLevelTest extends KernelTestCase
{

    /**
     * @var SkillLevel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SkillLevel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\SkillLevel::setTitle
     * @covers Com\Nairus\ResumeBundle\Entity\SkillLevel::getTitle
     */
    public function testGetAndSetTitle()
    {
        try {
            $this->object->setTitle("Title");
            $this->assertSame("Title", $this->object->getTitle());
        } catch (\Exception $exc) {
            $this->fail("Aucune exception ne doit être levée :" . $exc->getMessage());
        }
    }

    /**
     * @covers Com\Nairus\ResumeBundle\Entity\SkillLevel::setTitle
     *
     * @expectedException \TypeError
     */
    public function testSetTitleWithNullParam()
    {
        $this->object->setTitle(null);
    }

}
