news_index:
    path:     /{page}
    defaults:
        _controller: "NSCoreBundle:News:index"
        page: 1
    requirements:
        page: \d*
    methods:  GET

news_show:
    path:     /{id}/show
    defaults: { _controller: "NSCoreBundle:News:show" }
    methods:  GET

news_new:
    path:     /new
    defaults: { _controller: "NSCoreBundle:News:new" }
    methods:  [GET, POST]

news_edit:
    path:     /{id}/edit
    defaults: { _controller: "NSCoreBundle:News:edit" }
    methods:  [GET, POST]

news_delete:
    path:     /{id}/delete
    defaults: { _controller: "NSCoreBundle:News:delete" }
    methods:  DELETE

news_translation:
    path: /{id}/translation/{locale}
    defaults: { _controller: "NSCoreBundle:News:translation" }
    methods: [GET, POST]

news_publish:
    path: /{id}/publish
    defaults: { _controller: "NSCoreBundle:News:publish" }
    methods: [POST]