# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER:        [ROLE_AUTHOR]
        ROLE_ADMIN:       [ROLE_AUTHOR, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: "%user.pwd%"
                        roles: 'ROLE_USER'
                    admin:
                        password: "%admin.pwd%"
                        roles: 'ROLE_ADMIN'
                    nairus:
                        password: "%nairus.pwd%"
                        roles: 'ROLE_SUPER_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: in_memory
            http_basic: ~

    access_control:
        - { path: ^/news, role: ROLE_ADMIN }
