# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Com\Nairus\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_USER:        [ROLE_AUTHOR]
        ROLE_ADMIN:       [ROLE_AUTHOR, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: fos_user
            form_login:
                login_path: ns_user_login
                check_path: fos_user_security_check
                default_target_path: fos_user_profile_show
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: fos_user_security_logout
                target: /

            remember_me:
                secret: "%secret%"

    access_control:
        - { path: "^/([a-z]{2}\/)?restricted", role: ROLE_AUTHOR }
        - { path: "^/([a-z]{2}\/)?admin", role: ROLE_ADMIN }
        - { path: "^/([a-z]{2}\/)?sadmin", role: ROLE_SUPER_ADMIN }
        - { path: "^/([a-z]{2}\/)?login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/([a-z]{2}\/)?account/change-password$", role: IS_AUTHENTICATED_FULLY }
        - { path: "^/([a-z]{2}\/)?account/profile", role: IS_AUTHENTICATED_REMEMBERED }
