skill_index:
    path:     /{page}
    defaults:
        _controller: "NSResumeBundle:Skill:index"
        page: 1
    requirements:
        page: \d*
    methods:  GET

skill_show:
    path:     /{id}/show
    defaults: { _controller: "NSResumeBundle:Skill:show" }
    methods:  GET

skill_new:
    path:     /new
    defaults: { _controller: "NSResumeBundle:Skill:new" }
    methods:  [GET, POST]

skill_edit:
    path:     /{id}/edit
    defaults: { _controller: "NSResumeBundle:Skill:edit" }
    methods:  [GET, POST]

skill_delete:
    path:     /{id}/delete
    defaults: { _controller: "NSResumeBundle:Skill:delete" }
    methods:  DELETE
