## Parameters config for test only.

parameters:
    # internal email for testing
    mailer_user: nairus.from@test.com
    mailer_user_to: nairus.to@test.com

    # Salt for password (override the production salt).
    secret: ThisIsASecret

    # Limit for the news list.
    ns_core.news_limit: 1

    antispam_choices:
        good: 12fc7bb9b8d24566b51a90e748eb35d9
        bad:  23ab771164ed4db4a5b0641fc35e7fb2

    # Configuration for the ImageManager
    image_manager: &image_manager
        # Base directory for content uploads
        uploads_base_dir: '%kernel.project_dir%%directory_separator%var'
        # Relative directory for html links.
        relative_base_dir: '%directory_separator%tests%directory_separator%image_manager%directory_separator%'
        # Entities configuration
        entities:
            mock_image_entity:
                # size in pixel
                src_width: 160
                src_height: 160
                thb_width: 50
                thb_height: 50
                # crop in the middle after resize
                crop: true
            avatar:
                # size in pixel
                src_width: 160
                src_height: 160
                thb_width: 50
                thb_height: 50
                # crop in the middle after resize
                crop: false