## Parameters config for CoreBundle

parameters:
    # Limit for the last news tiles on the homepage.
    ns_core.last_news_limit: 3
    # Limit for the News list (Cf. NewsController::indexAction).
    ns_core.news_limit: 5
    # Limit for contact message list (Cf. ContactMessageController::indexAction).
    ns_core.contact_message_limit: 20
    dates_format:
        fr: EEE d MMM Y
        en: EEE, MMM d Y
    # Configuration for the ImageManager
    image_manager: &image_manager
        # Base directory for content uploads
        uploads_base_dir: '%kernel.project_dir%%directory_separator%web'
        # Relative directory for html links.
        relative_base_dir: '%directory_separator%uploads%directory_separator%'
        # Entities configuration
        entities:
            avatar:
                # size in pixel
                src_width: 160
                src_height: 160
                thb_width: 50
                thb_height: 50
                # crop in the middle after resize
                crop: false
