## Parameters config for test only.

parameters:
    # 123
    user.pwd: $2y$12$25sjDd0WhpPq9PvREKGU/uMeirtvIUCrrINlDqGTP./Lm9eCWMDRG
    #456
    admin.pwd: $2y$12$mI.RckkwKuVw/eP3nY3rJOWw67erev5taiptjVTbw0d/vndMCtfeG
    #789
    nairus.pwd: $2y$12$X8KWvna7ufQd1d/uGnHhmuEfqAdo8NqDb2RmRGCxDM7neMeXrYd7C
