ns_core_news:
    resource: "@NSCoreBundle/Resources/config/routing/news.yml"
    prefix:   /admin/news

ns_core_homepage:
    path:     /
    defaults: { _controller: NSCoreBundle:Homepage:index }

ns_core_contact:
    path:     /contact
    defaults: { _controller: NSCoreBundle:Contact:form }
    methods:  [GET, POST]

ns_core_sadmin_contact:
    resource: "@NSCoreBundle/Resources/config/routing/contactmessage.yml"
    prefix:   /sadmin/contact
