ns_core_news:
    resource: "@NSCoreBundle/Resources/config/routing/news.yml"
    prefix:   /news

ns_core_homepage:
    path:     /
    defaults: { _controller: NSCoreBundle:Homepage:index }

ns_core_contact:
    path:     /contact
    defaults: { _controller: NSCoreBundle:Homepage:contact }