services:
    Com\Nairus\CoreBundle\Controller\HomepageController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $newsService: "@ns_core.news_service"

    Com\Nairus\CoreBundle\Controller\NewsController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $newsService: "@ns_core.news_service"
            $logger: "@logger"
            $translator: "@translator"

    Com\Nairus\CoreBundle\Controller\ErrorController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $twig: '@twig'
            $debug: "%kernel.debug%"

    ns_core.news_service:
        public: true
        class: Com\Nairus\CoreBundle\Service\NewsService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
        calls:
            - [setAvailableLocales, ["%available_locales%"]]

    ns_core.image_manager:
        public: true
        class: Com\Nairus\CoreBundle\Manager\GDImageManager
        arguments:
            $config: "%image_manager%"
            $logger: "@logger"

    ns_core.image_entity_listener:
        public: true
        class: Com\Nairus\CoreBundle\Listener\ImageEntityListener
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
            $logger: "@logger"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setImageManager, ["@ns_core.image_manager"]]
