services:
    ns_core.news_service:
        public: true
        class: Com\Nairus\CoreBundle\Service\NewsService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
        calls:
            - [setAvailableLocales, ["%available_locales%"]]
