ns_resume_admin:
    resource: "@NSResumeBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

ns_resume_public:
    resource: "@NSResumeBundle/Resources/config/routing/public.yml"
    prefix:   /resume
