ns_resume_skill:
    resource: "@NSResumeBundle/Resources/config/routing/skill.yml"
    prefix:   /admin/skill

ns_resume_homepage:
    path:     /{page}
    defaults:
        _controller: NSResumeBundle:Public:index
        page: 1
    requirements:
        page: \d*
    methods: GET
