services:
    ns_resume.resume_status_listener:
        public: false
        class: Com\Nairus\ResumeBundle\Listener\ResumeStatusListener
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: nsresume.update.resume.status, method: onUpdateStatus}
            - {name: kernel.event_listener, event: nsresume.delete.resume.status, method: onDeleteStatus}

    ns_resume.resume_service:
        public: true
        class: Com\Nairus\ResumeBundle\Service\ResumeService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"

    ns_resume.skill_service:
        public: true
        class: Com\Nairus\ResumeBundle\Service\SkillService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"

    ns_resume.skill_level_service:
        public: true
        class: Com\Nairus\ResumeBundle\Service\SkillLevelService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
