services:
    Com\Nairus\ResumeBundle\Controller\EducationController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $logger: "@logger"
            $translator: "@translator"
            $eventDispatcher: "@event_dispatcher"

    Com\Nairus\ResumeBundle\Controller\ExperienceController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $logger: "@logger"
            $translator: "@translator"
            $eventDispatcher: "@event_dispatcher"

    Com\Nairus\ResumeBundle\Controller\ResumeController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $resumeService: "@ns_resume.resume_service"
            $logger: "@logger"
            $translator: "@translator"

    Com\Nairus\ResumeBundle\Controller\SkillController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $skillService: "@ns_resume.skill_service"
            $logger: "@logger"
            $translator: "@translator"

    Com\Nairus\ResumeBundle\Controller\SkillLevelController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $skillLevelService: "@ns_resume.skill_level_service"
            $logger: "@logger"
            $translator: "@translator"

    Com\Nairus\ResumeBundle\Listener\ResumeStatusListener:
        public: false
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
        tags:
            - {name: kernel.event_listener, event: nsresume.update.resume.status, method: onUpdateStatus}

    ns_resume.resume_service:
        public: true
        class: Com\Nairus\ResumeBundle\Service\ResumeService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"

    ns_resume.skill_service:
        public: true
        class: Com\Nairus\ResumeBundle\Service\SkillService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"

    ns_resume.skill_level_service:
        public: true
        class: Com\Nairus\ResumeBundle\Service\SkillLevelService
        arguments:
            $entityManager: "@doctrine.orm.entity_manager"
